### ISSUE TITLE
Enable SASS/SCSS support?

### ISSUE THREAD

**Issue by danifornells** [tomhodgins/element-queries-spec#4]
Hi Tommy,
I am planning to use your awesome project, but I am wondering if it would be feasible to use SASS language, to take advantage of variables and mixins. In my oppinion, pre-processors like SASS are wide used on any size projects. The main compatibility problem between SASS and your project is the $ char in the meta-selectors. I made a test using underscore instead, and works perfectly. What's your oppinion?

`wrong-input.eqcss.scss`
```scss
$brand-color: #ff0000;
@element ".this-selector input" and (min-characters: 5) {
  $this { border-color: $brand-color; }
}
```

`right-input.eqcss.scss`
```scss
$brand-color: #ff0000;
@element ".this-selector input" and (min-characters: 5) {
  _this { border-color: $brand-color; }
}
```

`output.eqcss`
```css
@element ".this-selector input" and (min-characters: 5) {
  _this { border-color: #ff0000; }
}
```
